### ISSUE TITLE
可否将脚本整合为一个文件？

### ISSUE THREAD

**Issue by fky2015** [Aloxaf/10_0_0_55_login#1]
# 可否将脚本整合为一个文件？
原因如下
1. 如果是一个文件可以方便地放在${PATH}下的目录中，直接运行
2. NetworkManager 使用者 可以利用回调的功能来自动登录，比如：
```bash
# /etc/NetworkManager/dispatcher.d/90-script.sh
echo $CONNECTION_ID > /root/up
if [[ $CONNECTION_ID =~ "BIT-Web" ]]
then
	10_0_0_55_login login web > /tmp/BIT_login_res
elif [[ $CONNECTION_ID =~ "BeijingLG" ]]
then
	10_0_0_55_login login library > /tmp/BIT_login_res
fi
```

> 另外宿舍网线走的是Mobile

**Comment by Aloxaf** [comment]
这真是一个妙妙主意, 不如交给你吧(我这也没法测试啊......

**Comment by fky2015** [comment]
打算把这个放到pip上（10_0_0_55.py & support.py 本身），不知道这样合不合适？
另外打包应该是需要原作者来的，就靠您了，我先来本地安装的方法。

**Comment by Aloxaf** [comment]
@fky2015 行吧
话说单文件的话, 其实还有一个选择: https://github.com/Aloxaf/Rust-toys/tree/master/bitlogin (

**Comment by Aloxaf** [comment]
Fixed by 1cf3f6fe51833c720a282f075844b732ab7901d1
