### ISSUE TITLE
话说能不能三个方式依次认证，直到某个返回正常认证就停止。

### ISSUE THREAD

**Issue by fky2015** [Aloxaf/10_0_0_55_login#2]
这样好像用户就不用区分了emmmm

**Comment by Aloxaf** [comment]
(watch的东西太多, 不想看通知orz
关于这个问题, 其实唐老板有 [特殊的技巧](https://github.com/felinae98/10_0_0_55_login/blob/master/10_0_0_55.py#L102_L111)
你试试能不能用?

**Comment by Aloxaf** [comment]
Fixed by 1cf3f6fe51833c720a282f075844b732ab7901d1
